autolabeler:
  - label: 'staging'
    branch:
      - '/^develop$/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'

template: |
  $CHANGES

categories:
  - title: '🪐 Staging Releases'
    labels:
      - 'staging'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

